MAX_GENRE_NAME_LENGTH = 200
MAX_BOOK_TITLE_LENGTH = 200
MAX_BOOK_SUMMARY_LENGTH = 1000
MAX_BOOK_IMPRINT_LENGTH = 200
MAX_ISBN_LENGTH = 13
MAX_AUTHOR_NAME_LENGTH = 100

LOAN_STATUS = (
    ("m", "Maintenance"),
    ("o", "On loan"),
    ("a", "Available"),
    ("r", "Reserved"),
)

LOAN_STATUS_AVAILABLE = "a"
LOAN_STATUS_ON_LOAN = "o"
LOAN_STATUS_MAINTENANCE = "m"
LOAN_STATUS_RESERVED = "r"

BOOK_PAGINATE_BY = 2

